name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    # Utile si tu utilises Testcontainers (Docker est dispo sur ubuntu-latest)
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Temurin JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      # (Optionnel) Si tu as des snapshots récents ou caches invalides
      # - run: mvn -B -ntp -U -q help:evaluate -Dexpression=project.version

      - name: Build & Test (unit + IT)
        run: mvn -B -ntp -DskipTests=false verify

      # Rapports tests en artefacts pour consultation rapide depuis l’UI GH
      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**

      # (Optionnel) JaCoCo -> publie le rapport HTML comme artefact
      - name: Upload JaCoCo coverage (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: "**/target/site/jacoco/**"